routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\CustomersController;
use App\Http\Controllers\Admin\ForgotController;
use App\Http\Controllers\Admin\ChangePasswordController;

use App\Http\Controllers\Admin\PhonesController;
use App\Http\Controllers\Admin\LaptopsController;
use App\Http\Controllers\Admin\HeadphonesController;
use App\Http\Controllers\Admin\TabletsController;

use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\Order_detailController;






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [LoginController::class, 'index'])->name('admin');
Route::get('login', [LoginController::class, 'index']);
Route::post('login', [LoginController::class, 'login'])->name('login');
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('forgot_password', [ForgotController::class, 'forgot'])->name('forgot');
Route::post('forgot_password', [ForgotController::class, 'password'])->name('password');
Route::post('forgot_password/resetPassAll', [ForgotController::class, 'resetPassAll'])->name('resetPassAll');

Route::group(['middleware' => ['auth'], 'as' => 'admin.'], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);
    Route::resource('customers', CustomersController::class);
    Route::resource('phones', PhonesController::class);
    Route::resource('laptops', LaptopsController::class);
    Route::resource('headphones', HeadphonesController::class);
    Route::resource('tablets', TabletsController::class);

    Route::resource('orders', OrdersController::class);
    Route::resource('order_detail', Order_detailController::class);
    // Route::get('/order_detail/{id}', [Order_detailController::class, 'index']);
    

    Route::get('history', [HistoryController::class, 'history'])->name('history');



    Route::resource('ChangePassword', ChangePasswordController::class);
    Route::get('/change-password', [ChangePasswordController::class, 'index'])->name('passwordChange');
    Route::post('/change-password', [ChangePasswordController::class, 'changepassword'])->name('passwordUpdate');

    Route::delete('/users/delete/{id}', [UserController::class, 'destroy']);
    Route::delete('/customers/delete/{id}', [CustomersController::class, 'destroy']);

    Route::delete('/phones/delete/{id}', [PhonesController::class, 'destroy']);
    Route::delete('/laptops/delete/{id}', [LaptopsController::class, 'destroy']);
    Route::delete('/headphones/delete/{id}', [HeadphonesController::class, 'destroy']);
    Route::delete('/tablets/delete/{id}', [TabletsController::class, 'destroy']);
    Route::delete('/orders/delete/{id}', [OrdersController::class, 'destroy']);
    

    Route::get('users/{id}/profile', [UserController::class, 'getProfile'])->name('users.profile');


    Route::get('users/{id}/profile', [UserController::class, 'getProfile'])->name('users.profile');
    Route::get('change-language/{language}', [LanguageController::class, 'changeLanguage'])->name('change-language');

 
    Route::post('/users/update/{id}', [UserController::class, 'updateStatus']);

    Route::post('/phones/update/{id}', [PhonesController::class, 'updateStatus']);

    Route::post('/laptops/update/{id}', [LaptopsController::class, 'updateStatus']);

    Route::post('/tablets/update/{id}', [TabletsController::class, 'updateStatus']);

    Route::post('/headphones/update/{id}', [HeadphonesController::class, 'updateStatus']);
    
    


});
// ----------------------------------------------------------frontend-----------------------------------------------------


use App\Http\Controllers\FE\HomeController;
use App\Http\Controllers\FE\PhoneController;
use App\Http\Controllers\FE\LaptopController;

use App\Http\Controllers\FE\NotController;



Route::resource('/trang-chu', HomeController::class);

Route::resource('/dien-thoai', PhoneController::class);
Route::resource('/laptop', LaptopController::class);


Route::resource('/dong-ho', NotController::class);
Route::resource('/phu-kien', NotController::class);
Route::resource('/tin-tuc', NotController::class);
Route::resource('/sua-chua', NotController::class);
Route::resource('/sim-the', NotController::class);
Route::resource('/khuyen-mai', NotController::class);

app/Models/Laptops.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Laptops extends Model
{
    use HasFactory, SoftDeletes;
    protected $table = 'laptops';
    protected $fillable = ['name','code','origin','price','picture','status','configuration','description'];
    public function scopeSearch($query, $data)
    {
        $paging_number = 10;
        if (isset($data)) {
            foreach ($data as $key => $value) {
                if (isset($value)) {
                    switch ($key) {
                        case 'q':
                            $query->where(function ($q) use ($value) {
                                $q->where('name', 'LIKE', "%$value%")->orWhere('price', 'LIKE', "%$value%")->orWhere('origin', 'LIKE', "%$value%");
                            });
                            break;
                        case 'status':
                            $query->where('status', $value);
                            break;
                     
                    }
                }
            }
        }
       

        return $query->orderBy('created_at', 'desc')->paginate($paging_number);
    }
}

app/Http/Controllers/Admin/LaptopsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Laptops;
use Carbon\Carbon;
use App\Http\Requests\LaptopsRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class LaptopsController extends Controller

{

    public function index()
    {

        $paging_number = 10;
        $data = request()->post();
        $laptops = Laptops::search($data);


        return view('admin.laptops.list', compact('laptops'))
            ->with('i', (request()->input('page', 1) - 1) * $paging_number);
    }

    public function show($id)
    {
        $laptops = Laptops::find($id);
        return view('admin.laptops.show', compact('laptops'));
    }

    public function create()
    {
        return view('admin.laptops.create');
    }

    public function store(LaptopsRequest $request)
    {

        $data = $request->all();
        $request->validate([
            'picture' => 'required|mimes:png,jpg,jpeg,svg|max:2048',
        ]);
        if (!empty($data['picture'])) {
            $fileName = time() . '.' . $request->picture->extension();
            $request->picture->move(public_path('img'), $fileName);
            $data['picture'] = $fileName;
        }
        Laptops::create($data);

        return redirect()->route('admin.laptops.index')
            ->with('success', 'Laptops created successfully.');
    }



    public function edit($id)
    {
        $laptops = Laptops::find($id);
        return view('admin.Laptops.edit', compact('laptops'));
    }
    public function update(LaptopsRequest $request, $id)
    {   
        $data = $request->all();
  
        if(!empty($data['picture'])){
            $request->validate([
                'picture' => 'required|mimes:png,jpg,jpeg,svg|max:2048',
            ]);
            $fileName = time() . '.' . $request->picture->extension();
            $request->picture->move(public_path('img'), $fileName);
            $data['picture'] = $fileName;
        }
        $laptops = Laptops::find($id);
        $laptops->update($data);
        return redirect()->route('admin.laptops.index')
            ->with('success', 'Laptops updated successfully');
    }
    public function destroy($id)
    {

        $result = Laptops::find($id);
        $result->delete();
        $result->roles()->detach();
        return json_encode(['success' => 'deleted successfully']);
    }

    public function updateStatus($id)
    {
        $laptops = Laptops::where('id', $id)->first();
        if ($laptops->status == 0) {
            $laptops->update(['status' => 1]);
        } else {
            $laptops->update(['status' => 0]);
        }
        return json_encode(['success' => 'update successfully']);
    }
}

app/Http/Controllers/Api/LaptopsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\LaptopsRequest;
use App\Http\Resources\Api\LaptopsResource;
use App\Models\Laptops;

class LaptopsController extends Controller
{
    public function index(){
        $paging_number = Laptops::paginate(10);
        return LaptopsResource::collection($paging_number);
    }
    public function show($id)
    {
        $result = Laptops::find($id);
        return new LaptopsResource($result);
    }

    public function store(LaptopsRequest $request){
        try {
            $result = new Laptops();
            $result->fill($request->validated())->save();

            return new LaptopsResource($result);
        } catch (\Exception $exception) {
            return response()->json(['message' => 'Could not create a new user', 'error' => "Invalid data - {$exception->getMessage()}"], 400);
        }
    }

    public function update(LaptopsRequest $request, $id)
    {
        $result = Laptops::find($id);

        if (!empty($result)) {
            $result->fill($request->validated())->save();

            return new LaptopsResource($result);
        } else {
            return response()->json(['message' => 'Acc not found'], 404);
        }
    }

    public function destroy($id)
    {
        $result = Laptops::find($id);

        if (!empty($result)) {
            $result->delete();
        }

        return response()->json(null, 204);
    }
}

app/Http/Controllers/FE/LaptopController.php
<?php

namespace App\Http\Controllers\FE;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Laptops;

class LaptopController extends Controller
{
    public function index(){
           
          $laptops = Laptops::all();
          
          return view('fe.listlaptop', compact('laptops'));
    }
 
}

resources/views/admin/laptops/create.blade.php
@extends('layouts.admin.app')

@section('title', 'Laptop')

@section('main-content')

@if ($errors->any())
<div class="alert alert-danger border-left-danger" role="alert">
    <ul class="pl-4 my-2">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="row">
    <div class="col-lg-12 order-lg-1">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-success">Thông tin sản phẩm</h6>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('admin.laptops.store') }}" autocomplete="off" id="myform" enctype="multipart/form-data">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="name">Tên sản phẩm<span class="small text-danger">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" value="{{ old('name') }}" maxlength="500" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="origin">Xuất xứ<span class="small text-danger">*</span></label>
                                    <input type="text" id="origin" class="form-control" name="origin" value="{{ old('origin') }}" maxlength="500" required>
                                </div>
                            </div>

                        </div>


                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="code">Mã sản phẩm<span class="small text-danger">*</span></label>
                                    <input type="text" id="code" class="form-control" name="code" value="{{ old('code') }}" maxlength="500" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="picture">Ảnh sản phẩm<span class="small text-danger">*</span></label>
                                    <input type="file" id="picture" class="form-control" name="picture" value="{{ old('picture') }}" maxlength="500" required>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-labe l" for="price">Giá tiền<span class="small text-danger">*</span></label>
                                    <input type="text" id="price" class="form-control" name="price" value="{{ old('price') }}" maxlength="500" required>
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <label class="form-control-label" for="status">Trạng thái</label>
                                <select class="form-control custom-select" name="status" style="width:100%;">
                                    <option value="1" @if (old('status')==0) selected="selected" @endif>
                                        Hoạt động</option>
                                    <option value="0" @if (old('status')==1) selected="selected" @endif>
                                        Không hoạt động</option>

                                </select>
                            </div>


                        </div>


                        <div class="row mt-5">
                            <div class="col-lg-12">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="description" style="margin-top: -26px;">Mô tả

                                    </label>
                                    <textarea rows="5" id="description" class="form-control rich-text" name="description" maxlength="500">{{ old('description') }}</textarea>
                                </div>
                            </div>
                        </div>
                     
                        <div class="row mt-5">
                            <div class="col-lg-12">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="configuration" style="margin-top: -26px;">Cấu hình
                                    </label>
                                    <textarea rows="5" id="configuration" class="form-control rich-text" name="configuration" maxlength="500">{{ old('configuration') }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col text-left">
                                <button type="submit" class="btn btn-success save submit">Tạo Mới</button>
                                <a href="{{ route('admin.laptops.index') }}" class="btn btn-secondary">Thoát</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>




@endsection

resources/views/admin/laptops/edit.blade.php
@extends('layouts.admin.app')

@section('title', 'Laptop')

@section('main-content')

@if ($errors->any())
<div class="alert alert-danger border-left-danger" role="alert">
    <ul class="pl-4 my-2">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="row">
    <div class="col-lg-12 order-lg-1">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-success">Thông tin sản phẩm</h6>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('admin.laptops.update', $laptops->id) }}" autocomplete="off" id="myform" enctype="multipart/form-data">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="_method" value="PUT">
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="name">Tên sản phẩm<span class="small text-danger">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" value="{{ old('name', $laptops->name) }}" maxlength="500" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="origin">Xuất xứ<span class="small text-danger">*</span></label>
                                    <input type="text" id="origin" class="form-control" name="origin" value="{{ old('origin', $laptops->origin) }}" maxlength="500" required>
                                </div>
                            </div>

                        </div>


                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="code">Mã sản phẩm<span class="small text-danger">*</span></label>
                                    <input type="text" id="code" class="form-control" name="code" value="{{ old('code', $laptops->code) }}" maxlength="500" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="picture">Ảnh sản phẩm</label>
                                    <input type="file" id="picture" class="form-control" name="picture" value="" maxlength="500">
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="price">Giá tiền<span class="small text-danger">*</span></label>
                                    <input type="text" id="price" class="form-control" name="price" value="{{ old('price', $laptops->price) }}" maxlength="500" required>
                                </div>
                            </div>




                        </div>


                        <div class="row mt-5">
                            <div class="col-lg-12">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="description" style="margin-top: -26px;">Mô tả

                                    </label>
                                    <textarea rows="10" id="description" class="form-control rich-text" name="description" maxlength="500">{{ old('description', $laptops->description)  }}</textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row mt-5">
                            <div class="col-lg-12">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="configuration" style="margin-top: -26px;">
                                        Cấu hình
                                    </label>
                                    <textarea rows="10" id="configuration" class="form-control rich-text" name="configuration" maxlength="500">{{ old('configuration', $laptops->configuration)  }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col text-left">
                                <button type="submit" class="btn btn-success save submit">Lưu</button>
                                <a href="{{ route('admin.laptops.index') }}" class="btn btn-secondary">Thoát</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>




@endsection

resources/views/admin/laptops/list.blade.php
@extends('layouts.admin.app')

@section('title', 'Laptop')

@section('main-content')

@include('admin.laptops.search', ['route' => route('admin.laptops.index')])
<form method="post">
    @csrf
    @method('POST')
    <div class="action-list col-12 mb-2" style="display:flex; justify-content:space-between; align-items: center;">
        <div class="amount-user">
            @if ($laptops->total() <= 0) @else {!! $laptops->total() !!} Laptop
                @endif
        </div>
        <div class="text-right">
            <a href="{{ route('admin.laptops.create') }}" class="text-success">Tạo mới</a>
        </div>
    </div>
    @if (session('successMsg'))
    <div class="alert alert-success" role="alert">
        {{ session('successMsg') }}
    </div>
    @endif
    <div class="card">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table m-0">
                    <thead>
                        <tr>

                            <th width="2%">ID</th>
                            <th>Tên sản phẩm</th>
                            <th class="text-center" style="width:20%;">Ảnh sản phẩm</th>
                            <th>Xuất xứ</th>
                            <th>Giá tiền</th>
                            <th>Trạng thái</th>
                            <th width="12%">
                                <form action="">Chức năng</form>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if ($laptops->total() <= 0) <tr>
                            <td colspan="8" class="text-center text-danger bg-danger">
                                Không có giữ liệu
                            </td>
                            </tr>
                            @else
                            @foreach ($laptops as $item)

                            <tr>

                                <td>{{ $item->id }}</td>
                                <td>{{ $item->name }}</td>
                                <td>
                                    <img src="{{ asset('img/'. $item->picture) }}" alt="sanpham" class="mx-auto d-block w-50">
                                </td>
                                <td>{{ $item->origin }}</td>
                                <td>{{ currency_format($item->price) }}</td>
                                <td>
                                    @if ($item->status === 1)
                                    <span class="badge badge-success">Hoạt động</span>
                                    @else
                                    <span class="badge badge-danger">Không hoạt động</span>
                                    @endif
                                </td>
                                <td>
                                    <form action="{{ route('admin.laptops.destroy', $item->id) }}" method="POST" style="float: left; margin-right: 7px">
                                        <a class="btn btn-success btn-sm mr-1" href="{{ route('admin.laptops.edit', $item->id) }}"><i class="fas fa-pencil-alt"></i></a>
                                        <a href="javascript:void(0)" class="btn btn-danger btn-sm delete-d" id="{{ $item->id }}" data="laptops"><i class="fas fa-trash"></i></a>
                                    </form>

                                    {{-- //Modal Delete --}}
                                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">
                                                        Bạn có muốn xóa không ?
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <h5>Bạn có chắc chắn không ?</h5>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Thoát</button>
                                                    <button type="button" class="btn btn-success" id="confirm-delete">Đồng ý</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="{{ $item->id }}" class="status" data="laptops">
                                        @if ($item->status === 1)
                                        <a href="javascript:void(0)" class="btn btn-secondary btn-sm" title="Inactive"><i class="fas fa-minus-square"></i></a>
                                        @else
                                        <a href="javascript:void(0)" class="btn btn-success btn-sm" title="Active"><i class="fas fa-plus-square"></i></a>
                                        @endif
                                    </div>

                                </td>
                            </tr>

                            <div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">
                                                Bạn có muốn thay đổi không ?
                                            </h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <h5>Thay đổi trạng thái</h5>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancel">Thoát</button>
                                            <button type="button" class="btn btn-success" id="confirm-change">Đồng ý</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                            @endif
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</form>
<div class="row">
    @if ($laptops->total() <= 0) <p>
        </p>
        @else
        <div class="col-6">
            Hiển thị : {!! $laptops->currentPage() * $laptops->perPage() - $laptops->perPage() + 1 !!} - {!! $laptops->currentPage() * $laptops->perPage() - $laptops->perPage() + $laptops->count() !!}
            của {!! $laptops->total() !!}
        </div>
        <div class="col-6">
            <div class="float-right">
                {!! $laptops->appends(request()->except(['page', '_token']))->links() !!}
            </div>
        </div>
        @endif
</div>











@endsection

<?php
function currency_format($number, $suffix = '')
{
    if (!empty($number)) {
        return number_format($number, 0, ',', ',') . "{$suffix}";
    }
}
?>