routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\CustomersController;
use App\Http\Controllers\Admin\ForgotController;
use App\Http\Controllers\Admin\ChangePasswordController;

use App\Http\Controllers\Admin\PhonesController;
use App\Http\Controllers\Admin\LaptopsController;
use App\Http\Controllers\Admin\HeadphonesController;
use App\Http\Controllers\Admin\TabletsController;

use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\Order_detailController;






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [LoginController::class, 'index'])->name('admin');
Route::get('login', [LoginController::class, 'index']);
Route::post('login', [LoginController::class, 'login'])->name('login');
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('forgot_password', [ForgotController::class, 'forgot'])->name('forgot');
Route::post('forgot_password', [ForgotController::class, 'password'])->name('password');
Route::post('forgot_password/resetPassAll', [ForgotController::class, 'resetPassAll'])->name('resetPassAll');

Route::group(['middleware' => ['auth'], 'as' => 'admin.'], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);
    Route::resource('customers', CustomersController::class);
    Route::resource('phones', PhonesController::class);
    Route::resource('laptops', LaptopsController::class);
    Route::resource('headphones', HeadphonesController::class);
    Route::resource('tablets', TabletsController::class);

    Route::resource('orders', OrdersController::class);
    Route::resource('order_detail', Order_detailController::class);
    // Route::get('/order_detail/{id}', [Order_detailController::class, 'index']);
    

    Route::get('history', [HistoryController::class, 'history'])->name('history');



    Route::resource('ChangePassword', ChangePasswordController::class);
    Route::get('/change-password', [ChangePasswordController::class, 'index'])->name('passwordChange');
    Route::post('/change-password', [ChangePasswordController::class, 'changepassword'])->name('passwordUpdate');

    Route::delete('/users/delete/{id}', [UserController::class, 'destroy']);
    Route::delete('/customers/delete/{id}', [CustomersController::class, 'destroy']);

    Route::delete('/phones/delete/{id}', [PhonesController::class, 'destroy']);
    Route::delete('/laptops/delete/{id}', [LaptopsController::class, 'destroy']);
    Route::delete('/headphones/delete/{id}', [HeadphonesController::class, 'destroy']);
    Route::delete('/tablets/delete/{id}', [TabletsController::class, 'destroy']);
    Route::delete('/orders/delete/{id}', [OrdersController::class, 'destroy']);
    

    Route::get('users/{id}/profile', [UserController::class, 'getProfile'])->name('users.profile');


    Route::get('users/{id}/profile', [UserController::class, 'getProfile'])->name('users.profile');
    Route::get('change-language/{language}', [LanguageController::class, 'changeLanguage'])->name('change-language');

 
    Route::post('/users/update/{id}', [UserController::class, 'updateStatus']);

    Route::post('/phones/update/{id}', [PhonesController::class, 'updateStatus']);

    Route::post('/laptops/update/{id}', [LaptopsController::class, 'updateStatus']);

    Route::post('/tablets/update/{id}', [TabletsController::class, 'updateStatus']);

    Route::post('/headphones/update/{id}', [HeadphonesController::class, 'updateStatus']);
    
    


});
// ----------------------------------------------------------frontend-----------------------------------------------------


use App\Http\Controllers\FE\HomeController;
use App\Http\Controllers\FE\PhoneController;
use App\Http\Controllers\FE\LaptopController;

use App\Http\Controllers\FE\NotController;



Route::resource('/trang-chu', HomeController::class);

Route::resource('/dien-thoai', PhoneController::class);
Route::resource('/laptop', LaptopController::class);


Route::resource('/dong-ho', NotController::class);
Route::resource('/phu-kien', NotController::class);
Route::resource('/tin-tuc', NotController::class);
Route::resource('/sua-chua', NotController::class);
Route::resource('/sim-the', NotController::class);
Route::resource('/khuyen-mai', NotController::class);

app/Models/Order_detail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Order_detail extends Model
{
    use HasFactory, SoftDeletes;
    protected $table = 'order_detail';
    protected $fillable = ['tablet_id','phone_id','laptop_id','headphone_id','order_id','price','quantity','description','status'];
    public function scopeSearch($query, $data)
    {
        $paging_number = 10;

        if (!empty($data)) {
            foreach ($data as $key => $value) {
                if(!empty($value)) {
                    switch ($key) {
                        case 'q':
                            $query->where(function ($q) use ($value) {
                                $q->where('phone', 'LIKE', "%$value%")->orWhere('customers.full_name', 'LIKE', '%' . $value . '%')->join('customers', $this->table . '.customer_id', '=', 'customers.id');
                            });
                            break;
                        case 'gender':
                            $query->where('gender', $value);
                            break;
                    }
                }
            }
        }

        return $query->orderBy('created_at', 'desc')->paginate($paging_number);
    }
}

app/Http/Controllers/Admin/Order_detailController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Order_detail;
use Carbon\Carbon;
use App\Http\Requests\Order_detailRequest;
use App\Http\Controllers\Controller;
use App\Models\Phones;
use App\Models\Laptops;
use Illuminate\Support\Facades\DB;

class Order_detailController extends Controller

{

    public function index()
    {
    
        $paging_number = 10;
        $data = request()->post();
        $orders = Order_detail::search($data);
      
        return view('admin.order_detail.list', compact('orders'))
            ->with('i', (request()->input('page', 1) - 1) * $paging_number);
    }
    public function show($id)
    {    
       
        $phones = Phones::all();
        $laptops = Laptops::all();
        
        $order_detail = DB::table('order_detail')->where('order_id', $id)->get();
    
        return view('admin.order_detail.list', compact('order_detail','laptops','phones'));
    }
    public function create()
    {
        return view('admin.orders.create');
    }

    public function store(Order_detailRequest $request)
    {   
       
        $data = $request->all();
        Order_detail::create($data);
        return redirect()->route('admin.orders.index')
            ->with('success', 'orders created successfully.');
    }

    

    public function edit($id)
    {
        $orders = Order_detail::find($id);
        return view('admin.orders.edit', compact('orders'));
    }
    public function update(Order_detailRequest $request, $id)
    {
            $orders = Order_detail::find($id);
            $orders->update($request->all());
            return redirect()->route('admin.orders.index')
                ->with('success', 'orders updated successfully');
       
    }
    public function destroy($id)
    { 

        $result = Order_detail::find($id);
        $result->delete();
        $result->roles()->detach();
        return json_encode(['success' => 'deleted successfully']);
    }

}

app/Http/Controllers/Api/Order_detailController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Order_detailRequest;
use App\Http\Resources\Api\Order_detailResource;
use App\Models\Order_detail;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
class Order_detailController extends Controller
{
    public function index(){

        $paging_number = Order_detail::paginate(10);
        return Order_detailResource::collection($paging_number);
    }
    public function show($id)
    {
        $result = Order_detail::find($id);
        return new Order_detailResource($result);
    }
    public function store(Order_detailRequest $request){
        
        try {
            $result = new Order_detail();
     
            $result->fill($request->validated())->save();
             return new Order_detailResource($result);

        } catch (\Exception $exception) {
            return response()->json(['message' => 'Could not create a new order_detail', 'error' => "Invalid data - {$exception->getMessage()}"], 400);
        }
    }

    public function update(Order_detailRequest $request, $id)
    {
        $result = Order_detail::find($id);

        if (!empty($result)) {
            $result->fill($request->validated())->save();

            return new Order_detailResource($result);
        } else {
            return response()->json(['message' => 'Acc not found'], 404);
        }
    }

    public function destroy($id)
    {
        $result = Order_detail::find($id);

        if (!empty($result)) {
            $result->delete();
        }

        return response()->json(null, 204);
    }
}

resources/views/admin/order_detail/create.blade.php
@extends('layouts.admin.app')

@section('title', 'Đơn hàng')

@section('main-content')

@if ($errors->any())
<div class="alert alert-danger border-left-danger" role="alert">
    <ul class="pl-4 my-2">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="row">
    <div class="col-lg-12 order-lg-1">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-success">Thông tin đơn hàng</h6>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('admin.orders.store') }}" autocomplete="off" id="myform">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="full_name">Tên khách hàng<span class="small text-danger">*</span></label>
                                    <input type="text" id="name" class="form-control" name="full_name" value="{{ old('full_name') }}" maxlength="500" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="phone">Số điện thoại<span class="small text-danger">*</span></label>
                                    <input type="text" id="name" class="form-control" name="phone" value="{{ old('phone') }}" maxlength="500" required>
                                </div>
                            </div>


                        </div>
                        <div class="row ">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="email">Email<span class="small text-danger">*</span></label>
                                    <input type="email" id="name" class="form-control" name="email" value="{{ old('email') }}" maxlength="500" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <label class="form-control-label" for="gender">Giới tính</label>
                                <select class="form-control custom-select" name="gender" style="width:100%;">
                                    <option value="0" @if (old('gender')==0) selected="selected" @endif>
                                        Nữ</option>
                                    <option value="1" @if (old('gender')==1) selected="selected" @endif>
                                        Nam</option>

                                </select>
                            </div>
                        </div>
                       
                        <div class="row">

                            <div class="col-lg-12 ">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="address">Địa chỉ
                                        <span class="small text-danger">*</span>
                                    </label>
                                    <textarea rows="5" id="address" class="form-control" name="address" maxlength="500" required>{{ old('address') }}</textarea>
                                </div>
                            </div>
                        </div>
                        <hr class="bg-success">
                        <div class="row">
                            <div class="col-lg-6">
                                <label class="form-control-label" for="status">Trạng thái</label>
                                <select class="form-control custom-select" name="status" style="width:100%;">
                                    <option value="0" @if (old('status')==0) selected="selected" @endif>
                                        Mới</option>
                                    <option value="1" @if (old('status')==1) selected="selected" @endif>
                                        Thành công</option>
                                    <option value="2" @if (old('status')==2) selected="selected" @endif>
                                        Thất bại</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <label class="form-control-label" for="payment_methods">Phương thức thanh toán</label>
                                <select class="form-control custom-select" name="payment_methods" style="width:100%;">
                                    <option value="0" @if (old('payment_methods')==0) selected="selected" @endif>
                                        Chuyển khoản</option>
                                    <option value="1" @if (old('payment_methods')==1) selected="selected" @endif>
                                        Tiền mặt</option>

                                </select>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="price">Tổng tiền<span class="small text-danger">*</span></label>
                                    <input type="text" id="name" class="form-control" name="price" value="{{ old('price') }}" maxlength="500" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="description">Mô tả
                                        <span class="small text-danger">*</span>
                                    </label>
                                    <textarea rows="5" id="description" class="form-control" name="description" maxlength="500" required>{{ old('description') }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col text-left">
                                <button type="submit" class="btn btn-success save submit">Tạo Mới</button>
                                <a href="{{ route('admin.orders.index') }}" class="btn btn-secondary">Thoát</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/order_detail/edit.blade.php
@extends('layouts.admin.app')

@section('title', 'Đơn hàng')

@section('main-content')

@if ($errors->any())
<div class="alert alert-danger border-left-danger" role="alert">
    <ul class="pl-4 my-2">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
@if (session('errorMsg'))
<div class="alert alert-danger" role="alert">
    {{ session('errorMsg') }}
</div>
@endif
@if (session('successMsg'))
<div class="alert alert-success" role="alert">
    {{ session('successMsg') }}
</div>
@endif

<div class="row">
    <div class="col-lg-12 order-lg-1">

        <div class="card shadow mb-4">

            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-success">Thông tin đơn hàng</h6>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('admin.orders.update', $orders->id) }}" autocomplete="off" id="myform">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="_method" value="PUT">
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="customer_id">Tên khách hàng<span class="small text-danger">*</span></label>
                                    <input type="text" id="name" class="form-control" name="customer_id" value="{{ old('customer_id', $orders->customer_id) }}" maxlength="500" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="price">Tổng tiền<span class="small text-danger">*</span></label>
                                    <input type="text" id="name" class="form-control" name="price" value="{{ old('price', $orders->price) }}" maxlength="500" required>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label" for="status">Tình trạng đơn hàng
                                        <span class="small text-danger">*</span></label>
                                    <input type="text" id="status" class="form-control" name="status" placeholder="example@example.com" value="{{ old('status', $orders->status) }}" maxlength="200" required>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group focused">
                                    <label class="form-control-label" for="payment_methods">Hình thức thanh toán
                                        <span class="small text-danger">*</span>
                                    </label>
                                    <input type="text" id="payment_methods" class="form-control" name="payment_methods" value="{{ old('payment_methods', $orders->payment_methods) }}" minlength="10" maxlength="10" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-control-label" for="description">Mô tả
                                        <span class="small text-danger">*</span></label>
                                    <input type="text" id="description" class="form-control" name="description" placeholder="example@example.com" value="{{ old('description', $orders->description) }}" maxlength="200" required>
                                </div>
                            </div>
                        
                        </div>

                       
                    </div>
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col text-left">
                                <button type="submit" class="btn btn-success save">Lưu</button>

                                <a href="{{ route('admin.orders.index') }}" class="btn btn-secondary">Thoát</a>

                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/order_detail/list.blade.php
@extends('layouts.admin.app')

@section('title', 'Danh sách sản phẩm của đơn hàng')

@section('main-content')


<form method="post">
    @csrf
    @method('POST')

    <div class="card">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table m-0">
                    <thead>
                        <tr>

                            <th width="2%">#</th>
                            <th>Tên sản phẩm</th>
                            <th>Số lượng</th>
                            <th>Giá tiền</th>
                            <th width="12%">Trạng thái</th>

                            <th width="12%">
                                <form action="">Chức năng</form>
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($order_detail as $key => $item)
                        <tr>
                            <td>{{ $key +=1 }}</td>
                            @if($item->phone_id)
                            @foreach ($phones as $phone)
                            @if($item->phone_id == $phone->id)
                            <td>{{$phone->name}}</td>
                            @endif
                            @endforeach
                            @endif
                            @if($item->laptop_id)
                            @foreach ($laptops as $laptop)
                            @if($item->laptop_id == $laptop->id)
                            <td>{{$laptop->name}}</td>
                            @endif
                            @endforeach
                            @endif


                            <td>{{$item->quantity}}</td>
                            <td>{{ currency_format($item->price)}}</td>
                            <td>{{$item->status}}</td>

                            <td>
                                <form action="{{ route('admin.order_detail.destroy', $item->id) }}" method="POST" style="float: left; margin-right: 7px">
                                    <a class="btn btn-success btn-sm mr-1" href="{{ route('admin.order_detail.show', $item->id) }}"><i class="far fa-list-alt"></i></a>
                                    <a class="btn btn-success btn-sm mr-1" href="{{ route('admin.order_detail.edit', $item->id) }}"><i class="fas fa-pencil-alt"></i></a>
                                    <a href="javascript:void(0)" class="btn btn-danger btn-sm delete-d" id="{{ $item->id }}" data="order_detail"><i class="fas fa-trash"></i></a>
                                </form>

                                {{-- //Modal Delete --}}
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">
                                                    Bạn có muốn xóa không ?
                                                </h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <h5>Bạn có chắc chắn không ?</h5>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Thoát</button>
                                                <button type="button" class="btn btn-success" id="confirm-delete">Đồng ý</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </td>
                        </tr>


                        @endforeach

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</form>


@endsection


<?php
function currency_format($number, $suffix = '')
{
    if (!empty($number)) {
        return number_format($number, 0, ',', ',') . "{$suffix}";
    }
}
?>